### ISSUE TITLE
Dockerfile and docker-compose.yml

### ISSUE THREAD

**Issue by dustin-hawkins** [amborle/featmap#4]
I created a quick `Dockerfile` and docker-compose.yml, but could not get the build to work properly, so this reverts to downloading the release.

1. Create a `.env` file and put the appropriate release version
2. Create a `./config/conf.json` file according to your README
3. `docker-compose build`
4. `docker-compose up -d`

should be available on port 80.

Dockerfile
```FROM golang:buster
ARG featmap_version=1.0.5
RUN mkdir -p /opt/featmap && \
    echo "Fetching https://github.com/amborle/featmap/releases/download/v${featmap_version}/featmap-${featmap_version}-linux-amd64" && \
    wget -O /opt/featmap/featmap https://github.com/amborle/featmap/releases/download/v${featmap_version}/featmap-${featmap_version}-linux-amd64 && \
    chmod 775 /opt/featmap/featmap
ENTRYPOINT cd /opt/featmap && ./featmap
```

docker-compose.yml
```
version: "3"
services:
        postgres:
                container_name: pgsql-lc
                image: postgres:11-alpine
                restart: always
                environment:
                        POSTGRES_USER: featmap
                        POSTGRES_DB: featmap
                        POSTGRES_PASSWORD: password
        featmap:
                container_name: featmap
                image: amborle/featmap:v${FEATMAP_VERSION}
                restart: always
                build: 
                        context: .
                        dockerfile: Dockerfile
                        args:
                                - featmap_version=${FEATMAP_VERSION}
                depends_on: 
                        - postgres
                ports:
                        - 80:80
                volumes:
                        - ${PWD}/config/conf.json:/opt/featmap/conf.json
```

.env
```
FEATMAP_VERSION=1.0.5
```
